
version: 2
models:
  - name: stg_subscriptions
    columns:
      - name: sub_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['active', 'cancelled']
